//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventHorizon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Strategic")]
        public string StrategicMusicPath {
            get {
                return ((string)(this["StrategicMusicPath"]));
            }
            set {
                this["StrategicMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleFavorable")]
        public string BattleFavorableMusicPath {
            get {
                return ((string)(this["BattleFavorableMusicPath"]));
            }
            set {
                this["BattleFavorableMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleEqual")]
        public string BattleEqualMusicPath {
            get {
                return ((string)(this["BattleEqualMusicPath"]));
            }
            set {
                this["BattleEqualMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleUnfavorable")]
        public string BattleUnfavorableMusicPath {
            get {
                return ((string)(this["BattleUnfavorableMusicPath"]));
            }
            set {
                this["BattleUnfavorableMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleEndVictory")]
        public string BattleEndVictoryMusicPath {
            get {
                return ((string)(this["BattleEndVictoryMusicPath"]));
            }
            set {
                this["BattleEndVictoryMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleEndStalemate")]
        public string BattleEndStalemateMusicPath {
            get {
                return ((string)(this["BattleEndStalemateMusicPath"]));
            }
            set {
                this["BattleEndStalemateMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BattleEndDefeat")]
        public string BattleEndDefeatMusicPath {
            get {
                return ((string)(this["BattleEndDefeatMusicPath"]));
            }
            set {
                this["BattleEndDefeatMusicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double MusicFadeSeconds {
            get {
                return ((double)(this["MusicFadeSeconds"]));
            }
            set {
                this["MusicFadeSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double BattleFavorableThreshold {
            get {
                return ((double)(this["BattleFavorableThreshold"]));
            }
            set {
                this["BattleFavorableThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double BattleUnfavorableThreshold {
            get {
                return ((double)(this["BattleUnfavorableThreshold"]));
            }
            set {
                this["BattleUnfavorableThreshold"] = value;
            }
        }
    }
}
